<?php

/**
 * @file soc_timeline.module
 * TODO: Enter file description here.
 */

define('SOCTL_name', 'SoC Timeline ');
define('SOCTL_desc', 'Produces JavaScript time line using JQueryUI effects with trigger text [timeline:#divID]');
define('SOCTL_BTRSLD_FILE', 'SOCSlider.js');
define('SOCTL_BTRSLD_CSS', 'timeline-style.css');



/**
 * Implements hook_filter_info().
 */
function soc_timeline_filter_info() {
  $filters['soc_timeline_filter'] = array(
    'title' => t(SOCTL_name),
    'description' => t(SOCTL_desc),
    'process callback' => '_soc_timeline_process',
    'tips callback' => '_soc_timeline_filter_tips',


    );

  return $filters;
}



/*
See if there is a match to [timeline:#divID]. If so, inject the base javascript
file into Drupal's boot strap process.
*/
function _soc_timeline_process($text, $filter, $format, $langcode, $cache, $cache_id) {


  $re = "/\\[timeline:(#[A-Za-z]+)]/";
  preg_match_all($re, $text, $matches);

  $replace_original = $matches[0];
  $first_match      = $matches[1];

  /*
  If no match is found, stop processing and return unaltered text back to the
  caller.
  */
  if (! isset($first_match[0]) ){
    return $text;
  }

  /*
  Settings to pass to Javascript through Drupal.settings
  */
  $settings = array(
    'duration' => '1500',
    'prev_button' => ' #prev',
    'next_button' => ' #next'
    );
  drupal_add_js(array('soc_timeline'=>$settings), 'setting');

  // Inject javascript files
  drupal_add_js('https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js', 'external');
  drupal_add_js(drupal_get_path('module', 'soc_timeline') . '/' . SOCTL_BTRSLD_FILE, 'file');
  drupal_add_js("jQuery(function() { socslider = new SOCSlider('$first_match[0]', '#date' ); });", 'inline');

  // CSS file
  drupal_add_css(drupal_get_path('module', 'soc_timeline') . '/' . SOCTL_BTRSLD_CSS, array('group' => CSS_DEFAULT, 'type' => 'file'));

  /*
  Remove orginal text from the blob-o-text and return back to caller.
  */
  return str_replace($replace_original, '', $text);
}


function _soc_timeline_filter_tips($filter, $format, $long)  {
  return SOCTL_desc ;
}


